### ISSUE TITLE
Compatibilidade com Delphi XE 7

### ISSUE THREAD

**Issue by elvisbayerl** [HashLoad/horse-octet-stream#12]
Na procedure procedure GetAllDataAsStream(ARequest: THorseRequest; AStream: TMemoryStream);

Neste processo "ARequest.RawWebRequest.ReadTotalContent;", não tem este recurso no Delphi XE7, consegui solucionar a situação alterando o processo para.

  {$IF CompilerVersion <= 28}
    Assert(Length(ARequest.RawWebRequest.RawContent) = ARequest.RawWebRequest.ContentLength);
  {$ELSE}
    ARequest.RawWebRequest.ReadTotalContent;
  {$ENDIF}

Referência: https://github.com/danieleteti/delphimvcframework/issues/200

**Comment by viniciussanchez** [comment]
Legal... tem como enviar um pull request? 
Qualquer cosia alteramos aqui mesmo

**Comment by elvisbayerl** [comment]
Pode alterar Vinicius, na próxima eu envio um pull request.

**Comment by renanfrancisodasilva** [comment]
No XE8 também não existe esse recurso!
